### ISSUE TITLE
error start spark context with graphframe

### ISSUE THREAD

**Issue by joscani** [rstudio/graphframes#7]
Hi . I try to start with graphframe . My code is 

```
library(graphframes)
library(sparklyr)
library(dplyr)
# connect to spark using sparklyr
sc <- spark_connect(master = "local", version = "2.3.0")
```
But I get the following error

Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (7002): Gateway in port (8880) did not respond.

When I start sparklyr without import graphframes spark inits ok.

I've already seen this issue in sparklyr but I don't know how to solve. Any idea ?

**Comment by kevinykuo** [comment]
Could you share the full stack trace?

**Comment by joscani** [comment]
Sure. I unset the proxy setting in my .bashrc, and I see this error
```
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (10320): Gateway in port (8880) did not respond.
    Path: /home/jose/spark/spark-2.3.0-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'graphframes:graphframes:0.5.0-spark2.3-s_2.11', '/home/jose/R/x86_64-pc-linux-gnu-library/3.5/sparklyr/java/sparklyr-2.3-2.11.jar', 8880, 10320
    Log: /tmp/RtmpYlOBNp/file7bc52646554_spark.log

---- Output Log ----
Ivy Default Cache set to: /home/jose/.ivy2/cache
The jars for the packages stored in: /home/jose/.ivy2/jars
:: loading settings :: url = jar:file:/home/jose/spark/spark-2.3.0-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
:: resolution report :: resolve 647ms :: artifacts dl 0ms
	:: modules in use:
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		module not found: graphframes#graphframes;0.5.0-spark2.3-s_2.11

	==== local-m2-cache: tried

	  file:/home/jose/.m2/repository/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.pom

	  -- artifact graphframes#graphframes;0.5.0-spark2.3-s_2.11!graphframes.jar:

	  file:/home/jose/.m2/repository/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.jar

	==== local-ivy-cache: tried

	  /home/jose/.ivy2/local/graphframes/graphframes/0.5.0-spark2.3-s_2.11/ivys/ivy.xml

	  -- artifact graphframes#graphframes;0.5.0-spark2.3-s_2.11!graphframes.jar:

	  /home/jose/.ivy2/local/graphframes/graphframes/0.5.0-spark2.3-s_2.11/jars/graphframes.jar

	==== central: tried

	  https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.pom

	  -- artifact graphframes#graphframes;0.5.0-spark2.3-s_2.11!graphframes.jar:

	  https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.pom

	  -- artifact graphframes#graphframes;0.5.0-spark2.3-s_2.11!graphframes.jar:

	  http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: graphframes#graphframes;0.5.0-spark2.3-s_2.11: not found

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.pom (javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)

	Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.3-s_2.11/graphframes-0.5.0-spark2.3-s_2.11.jar (javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: graphframes#graphframes;0.5.0-spark2.3-s_2.11: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1270)
	at org.apache.spark.deploy.DependencyUtils$.resolveMavenDependencies(DependencyUtils.scala:49)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:350)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:170)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:136)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
```

**Comment by kevinykuo** [comment]
graphframes doesn't support Spark 2.3 yet, see https://github.com/graphframes/graphframes/issues/267

**Comment by kevinykuo** [comment]
There should be a better error message though, so let's leave this issue open to track the implementation of that.

**Comment by joscani** [comment]
uhmm. Maybe. I get the same mistake with spark 2.2.0, but It works with spark 2.0.0. In my company we are using spark 2.2.0 and it would be great use graphframes sparklyr extension with our data.



```
Error in force(code) : 
  Failed while connecting to sparklyr to port (8880) for sessionid (96912): Gateway in port (8880) did not respond.
    Path: /home/jose/spark/spark-2.2.0-bin-hadoop2.7/bin/spark-submit
    Parameters: --class, sparklyr.Shell, --packages, 'graphframes:graphframes:0.5.0-spark2.2-s_2.11', '/home/jose/R/x86_64-pc-linux-gnu-library/3.5/sparklyr/java/sparklyr-2.2-2.11.jar', 8880, 96912
    Log: /tmp/RtmpxV2cPb/file7db35c2965e_spark.log


---- Output Log ----
Ivy Default Cache set to: /home/jose/.ivy2/cache
The jars for the packages stored in: /home/jose/.ivy2/jars
:: loading settings :: url = jar:file:/home/jose/spark/spark-2.2.0-bin-hadoop2.7/jars/ivy-2.4.0.jar!/org/apache/ivy/core/settings/ivysettings.xml
graphframes#graphframes added as a dependency
:: resolving dependencies :: org.apache.spark#spark-submit-parent;1.0
	confs: [default]
:: resolution report :: resolve 637ms :: artifacts dl 0ms
	:: modules in use:
	---------------------------------------------------------------------
	|                  |            modules            ||   artifacts   |
	|       conf       | number| search|dwnlded|evicted|| number|dwnlded|
	---------------------------------------------------------------------
	|      default     |   1   |   0   |   0   |   0   ||   0   |   0   |
	---------------------------------------------------------------------

:: problems summary ::
:::: WARNINGS
		module not found: graphframes#graphframes;0.5.0-spark2.2-s_2.11

	==== local-m2-cache: tried

	  file:/home/jose/.m2/repository/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.pom

	  -- artifact graphframes#graphframes;0.5.0-spark2.2-s_2.11!graphframes.jar:

	  file:/home/jose/.m2/repository/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.jar

	==== local-ivy-cache: tried

	  /home/jose/.ivy2/local/graphframes/graphframes/0.5.0-spark2.2-s_2.11/ivys/ivy.xml

	  -- artifact graphframes#graphframes;0.5.0-spark2.2-s_2.11!graphframes.jar:

	  /home/jose/.ivy2/local/graphframes/graphframes/0.5.0-spark2.2-s_2.11/jars/graphframes.jar

	==== central: tried

	  https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.pom

	  -- artifact graphframes#graphframes;0.5.0-spark2.2-s_2.11!graphframes.jar:

	  https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.jar

	==== spark-packages: tried

	  http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.pom

	  -- artifact graphframes#graphframes;0.5.0-spark2.2-s_2.11!graphframes.jar:

	  http://dl.bintray.com/spark-packages/maven/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.jar

		::::::::::::::::::::::::::::::::::::::::::::::

		::          UNRESOLVED DEPENDENCIES         ::

		::::::::::::::::::::::::::::::::::::::::::::::

		:: graphframes#graphframes;0.5.0-spark2.2-s_2.11: not found

		::::::::::::::::::::::::::::::::::::::::::::::


:::: ERRORS
	Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.pom (javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)

	Server access error at url https://repo1.maven.org/maven2/graphframes/graphframes/0.5.0-spark2.2-s_2.11/graphframes-0.5.0-spark2.2-s_2.11.jar (javax.net.ssl.SSLException: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty)


:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
Exception in thread "main" java.lang.RuntimeException: [unresolved dependency: graphframes#graphframes;0.5.0-spark2.2-s_2.11: not found]
	at org.apache.spark.deploy.SparkSubmitUtils$.resolveMavenCoordinates(SparkSubmit.scala:1177)
	at org.apache.spark.deploy.SparkSubmit$.prepareSubmitEnvironment(SparkSubmit.scala:298)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:153)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:119)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)

---- Error Log ----
```

**Comment by kevinykuo** [comment]
Right, graphframes only supports Spark versions up to 2.1 https://mvnrepository.com/artifact/graphframes/graphframes
